from datetime import date, datetime

from employee.services.oracle_service import get_oracle_connection


def _to_oracle_date_optional(value):
    if value is None or value == "":
        return None
    return _to_oracle_date(value)


def _to_oracle_date(value):
    if value is None or value == "":
        return None
    if isinstance(value, date) and not isinstance(value, datetime):
        return value
    if hasattr(value, "date"):
        return value.date()
    text = str(value).strip()
    for fmt in ("%Y-%m-%d", "%d-%m-%Y"):
        try:
            return datetime.strptime(text, fmt).date()
        except ValueError:
            continue
    raise ValueError(f"Invalid date: {value!r}")


def get_next_appcn_no():
    """
    Oracle-side APPCN_NO generator.
    (Project currently uses MAX(TO_NUMBER(APPCN_NO))+1 in Oracle.)
    """
    conn = get_oracle_connection()
    cur = conn.cursor()
    try:
        cur.execute(
            "SELECT NVL(MAX(TO_NUMBER(APPCN_NO)),0) + 1 "
            "FROM FINANCE.FI_PN_MH_APPLICATION"
        )
        next_no = cur.fetchone()[0]
        return str(int(next_no))
    finally:
        cur.close()
        conn.close()


def upsert_fi_pn_mh_application_from_commutation(
    *,
    emp_cd,
    appcn_no,
    appcn_dt,
    application_time=None,
    comm_start_mnth=None,
    commutation_per=None,
    commutation_reasons="",
    impl_fpen_combill=None,
    impl_bill_no=None,
    ref_no=None,
    application_rcvd_dt=None,
    commutation_dt=None,
    restoration_dt=None,
    mo_certificate_dt=None,
    mo_certificate_ref=None,
    commutation_amt=None,
    pension_amt=None,
    user_code="SYS",
):
    """
    Insert/update FINANCE.FI_PN_MH_APPLICATION.
    APPCN_NO: generated by Oracle and stored locally.
    COMM_START_YR: derived from APPCN_DT.
    """
    if not emp_cd:
        raise ValueError("emp_cd is required")
    if not appcn_no:
        raise ValueError("appcn_no is required")
    if not appcn_dt:
        raise ValueError("appcn_dt is required")

    appcn_dt = _to_oracle_date(appcn_dt)
    comm_start_yr = int(appcn_dt.year)

    payload = {
        "APPCN_NO": str(appcn_no),
        "APPCN_DT": appcn_dt,
        "EMP_CD": str(emp_cd).strip(),
        "COMMUTATION_PER": commutation_per,
        "COMMUTATION_REASONS": commutation_reasons or None,
        "COMM_START_MNTH": comm_start_mnth,
        "COMM_START_YR": comm_start_yr,
        "IMPL_FPEN_COMBILL": impl_fpen_combill,
        "IMPL_BILL_NO": impl_bill_no or None,
        "REF_NO": ref_no or None,
        "MO_CERTIFICATE_REF": mo_certificate_ref,
        "MO_CERTIFICATION_DT": _to_oracle_date_optional(mo_certificate_dt),
        "APPLICATION_RCVD_DT": _to_oracle_date_optional(application_rcvd_dt),
        "COMMUTATION_DATE": _to_oracle_date_optional(commutation_dt),
        "RESTORATION_DT": _to_oracle_date_optional(restoration_dt),
        "APPLICATION_TIME": application_time,
        "COMMUTATION_AMT": commutation_amt,
        "PEN_AMT": pension_amt,
        "USER_CODE": (user_code or "SYS")[:5],
    }

    conn = get_oracle_connection()
    cur = conn.cursor()
    try:
        lookup_bind = {
            "EMP_CD": payload["EMP_CD"],
            "APPCN_NO": payload["APPCN_NO"],
        }
        cur.execute(
            """
            SELECT COUNT(*)
            FROM FINANCE.FI_PN_MH_APPLICATION
            WHERE EMP_CD = :EMP_CD AND APPCN_NO = :APPCN_NO
            """,
            lookup_bind,
        )
        exists = cur.fetchone()[0] > 0

        if exists:
            cur.execute(
                """
                UPDATE FINANCE.FI_PN_MH_APPLICATION
                SET APPCN_DT = :APPCN_DT,
                    COMMUTATION_PER = :COMMUTATION_PER,
                    COMMUTATION_REASONS = :COMMUTATION_REASONS,
                    COMM_START_MNTH = :COMM_START_MNTH,
                    COMM_START_YR = :COMM_START_YR,
                    IMPL_FPEN_COMBILL = :IMPL_FPEN_COMBILL,
                    IMPL_BILL_NO = :IMPL_BILL_NO,
                    REF_NO = :REF_NO,
                    MO_CERTIFICATE_REF = :MO_CERTIFICATE_REF,
                    MO_CERTIFICATION_DT = :MO_CERTIFICATION_DT,
                    APPLICATION_RCVD_DT = :APPLICATION_RCVD_DT,
                    COMMUTATION_DATE = :COMMUTATION_DATE,
                    RESTORATION_DT = :RESTORATION_DT,
                    APPLICATION_TIME = :APPLICATION_TIME,
                    COMMUTATION_AMT = :COMMUTATION_AMT,
                    PEN_AMT = :PEN_AMT,
                    DATE_MODIFIED = SYSDATE,
                    MODIFIED_BY = :USER_CODE
                WHERE EMP_CD = :EMP_CD AND APPCN_NO = :APPCN_NO
                """,
                payload,
            )
        else:
            cur.execute(
                """
                INSERT INTO FINANCE.FI_PN_MH_APPLICATION (
                    APPCN_NO, APPCN_DT, EMP_CD,
                    COMMUTATION_PER, COMMUTATION_REASONS,
                    COMM_START_MNTH, COMM_START_YR,
                    IMPL_FPEN_COMBILL, IMPL_BILL_NO, REF_NO,
                    MO_CERTIFICATE_REF, MO_CERTIFICATION_DT,
                    APPLICATION_RCVD_DT, COMMUTATION_DATE,
                    RESTORATION_DT, APPLICATION_TIME,
                    COMMUTATION_AMT, PEN_AMT,
                    DATE_CREATED, CREATED_BY
                ) VALUES (
                    :APPCN_NO, :APPCN_DT, :EMP_CD,
                    :COMMUTATION_PER, :COMMUTATION_REASONS,
                    :COMM_START_MNTH, :COMM_START_YR,
                    :IMPL_FPEN_COMBILL, :IMPL_BILL_NO, :REF_NO,
                    :MO_CERTIFICATE_REF, :MO_CERTIFICATION_DT,
                    :APPLICATION_RCVD_DT, :COMMUTATION_DATE,
                    :RESTORATION_DT, :APPLICATION_TIME,
                    :COMMUTATION_AMT, :PEN_AMT,
                    SYSDATE, :USER_CODE
                )
                """,
                payload,
            )

        conn.commit()
        return {"exists": exists, "appcn_no": payload["APPCN_NO"]}
    except Exception:
        conn.rollback()
        raise
    finally:
        cur.close()
        conn.close()

