# Generated by Django 5.2.12 on 2026-05-10 16:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PensionCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('emp_class', models.CharField(max_length=20)),
                ('birth_date', models.DateField()),
                ('joining_date', models.DateField()),
                ('retirement_date', models.DateField()),
                ('designation', models.CharField(max_length=200)),
                ('scale', models.CharField(max_length=100)),
                ('last_basic', models.DecimalField(decimal_places=2, max_digits=12)),
                ('no_pay_days', models.IntegerField(default=0)),
                ('dies_non_days', models.IntegerField(default=0)),
                ('commutation_percent', models.DecimalField(decimal_places=2, default=40, max_digits=5)),
                ('commutation_reason', models.CharField(blank=True, max_length=200, null=True)),
                ('status', models.CharField(default='INITIATED', max_length=50)),
                ('current_stage', models.CharField(default='CLERK', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pension_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pension_updated', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PensionSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_service_years', models.IntegerField(default=0)),
                ('total_service_months', models.IntegerField(default=0)),
                ('total_service_days', models.IntegerField(default=0)),
                ('tccs_years', models.IntegerField(default=0)),
                ('tccs_months', models.IntegerField(default=0)),
                ('tccs_days', models.IntegerField(default=0)),
                ('tqs_years', models.IntegerField(default=0)),
                ('tqs_months', models.IntegerField(default=0)),
                ('tqs_days', models.IntegerField(default=0)),
                ('pension_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('commutation_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('gratuity_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('pension_start_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pension_case', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='summary', to='first_pension.pensioncase')),
            ],
        ),
    ]
