# Generated by Django 5.2.12 on 2026-05-19 06:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_pension', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommutationApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_cd', models.CharField(max_length=20, unique=True)),
                ('appcn_no', models.IntegerField(default=0)),
                ('application_time', models.IntegerField(default=1)),
                ('comm_start_mnth', models.IntegerField(default=1)),
                ('appcn_dt', models.DateField()),
                ('application_rcvd_dt', models.DateField()),
                ('impl_fpen_combill', models.CharField(max_length=50)),
                ('commutation_dt', models.DateField()),
                ('restoration_dt', models.DateField()),
                ('commutation_per', models.IntegerField(default=0)),
                ('mo_certificate_dt', models.DateField()),
                ('mo_certificate_ref', models.CharField(max_length=50)),
                ('commutation_reasons', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='COMMUTATION INITIATED', max_length=50)),
                ('current_stage', models.CharField(default='PENSION USER', max_length=50)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commutation_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commutation_updated', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
