# Generated by Django 5.2.12 on 2026-05-21 09:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_pension', '0002_commutationapplication'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PensionProposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_cd', models.CharField(max_length=20, unique=True)),
                ('emp_name', models.CharField(blank=True, default='', max_length=200)),
                ('employee_status', models.CharField(default='EMPLOYEE', max_length=50)),
                ('ca_number', models.CharField(blank=True, default='', max_length=50)),
                ('pension_type', models.CharField(blank=True, default='', max_length=50)),
                ('pension_proposal_no', models.CharField(blank=True, default='', max_length=50)),
                ('eligible_double_family_pension', models.BooleanField(default=False)),
                ('separation_type', models.CharField(blank=True, default='', max_length=50)),
                ('separation_date', models.DateField(blank=True, null=True)),
                ('implemented_year', models.IntegerField(blank=True, null=True)),
                ('implemented_month', models.IntegerField(blank=True, null=True)),
                ('service_tenure', models.CharField(blank=True, default='', max_length=100)),
                ('pension_option', models.CharField(blank=True, default='', max_length=50)),
                ('option_given_by', models.CharField(blank=True, default='', max_length=50)),
                ('regn_no', models.CharField(blank=True, default='', max_length=50)),
                ('regn_date', models.DateField(blank=True, null=True)),
                ('start_month', models.IntegerField(blank=True, null=True)),
                ('start_year', models.IntegerField(blank=True, null=True)),
                ('pension_roll_no', models.CharField(blank=True, default='', max_length=50)),
                ('pension_proposal_date', models.DateField(blank=True, null=True)),
                ('double_family_pension_upto_date', models.DateField(blank=True, null=True)),
                ('provisional_pension_pct', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('bank_cd', models.CharField(blank=True, default='', max_length=20)),
                ('bank_name', models.CharField(blank=True, default='', max_length=200)),
                ('account_no', models.CharField(blank=True, default='', max_length=50)),
                ('vigilance_clearance_ref_no', models.CharField(blank=True, default='', max_length=100)),
                ('vigilance_clearance_ref_dt', models.DateField(blank=True, null=True)),
                ('lic_bank_cd', models.CharField(blank=True, default='', max_length=20)),
                ('lic_bank_name', models.CharField(blank=True, default='', max_length=200)),
                ('vr_ref_no', models.CharField(blank=True, default='', max_length=100)),
                ('vr_ref_dt', models.DateField(blank=True, null=True)),
                ('compassionate_allowance', models.CharField(blank=True, default='', max_length=50)),
                ('quarter_status', models.CharField(blank=True, default='', max_length=50)),
                ('nominee_eform', models.CharField(blank=True, default='', max_length=50)),
                ('compassionate_allowance_amt', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('port_city_resident', models.CharField(blank=True, default='', max_length=50)),
                ('gratuity_option', models.CharField(blank=True, default='', max_length=50)),
                ('retirement_cpi', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('id_card_submitted', models.BooleanField(default=False)),
                ('vigilance_cleared', models.BooleanField(default=False)),
                ('incentive_holder', models.CharField(blank=True, default='', max_length=50)),
                ('held_up_flag', models.CharField(blank=True, default='', max_length=50)),
                ('held_gratuity_amt', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('extra_tccs_enabled', models.BooleanField(default=False)),
                ('extra_tccs_years', models.IntegerField(default=0)),
                ('extra_tccs_months', models.IntegerField(default=0)),
                ('extra_tccs_days', models.IntegerField(default=0)),
                ('earning_deductions', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pension_proposal_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pension_proposal_updated', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
