# Generated by Django 5.2.12 on 2026-05-21 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_pension', '0003_pensionproposal'),
    ]

    operations = [
        migrations.AddField(
            model_name='pensioncase',
            name='no_pay_more_than_240_days',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pensioncase',
            name='suspension_days',
            field=models.IntegerField(default=0),
        ),
    ]
