# Generated by Django 5.2.12 on 2026-06-10 11:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_pension', '0008_commutationapplication_ca_ref_bill_sanction'),
    ]

    operations = [
        migrations.CreateModel(
            name='PensionProposalEarndedn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ca_number', models.CharField(blank=True, default='', max_length=22)),
                ('earndedn_cd', models.CharField(max_length=3)),
                ('earn_dedn_type', models.CharField(choices=[('E', 'Earning'), ('D', 'Deduction')], max_length=1)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('e_d_priority', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('deducted_amt', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('line_order', models.PositiveSmallIntegerField(default=0)),
                ('date_created', models.DateField(blank=True, null=True)),
                ('created_by', models.CharField(blank=True, default='', max_length=5)),
                ('date_modified', models.DateField(blank=True, null=True)),
                ('modified_by', models.CharField(blank=True, default='', max_length=5)),
            ],
            options={
                'verbose_name': 'Pension proposal earn/dedn line',
                'verbose_name_plural': 'Pension proposal earn/dedn lines',
                'db_table': 'fi_pn_md_pension_proposal',
                'ordering': ['line_order', 'id'],
            },
        ),
        migrations.RenameIndex(
            model_name='cachedretirementemployee',
            new_name='first_pensi_retirem_b547a8_idx',
            old_name='first_pensi_retire_6b2c8e_idx',
        ),
        migrations.RenameIndex(
            model_name='dashboardmonthsnapshot',
            new_name='first_pensi_year_d88318_idx',
            old_name='first_pensi_year_8a0f0d_idx',
        ),
        migrations.AlterField(
            model_name='pensionproposal',
            name='earning_deductions',
            field=models.JSONField(blank=True, default=list, help_text='Legacy JSON cache; canonical rows are in PensionProposalEarndedn.'),
        ),
        migrations.AddField(
            model_name='pensionproposalearndedn',
            name='proposal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='earndedn_lines', to='first_pension.pensionproposal'),
        ),
        migrations.AddConstraint(
            model_name='pensionproposalearndedn',
            constraint=models.UniqueConstraint(fields=('proposal', 'earndedn_cd'), name='uniq_proposal_earndedn_cd'),
        ),
    ]
