# Generated by Django 5.2.12 on 2026-06-15 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_pension', '0013_oracle_wave3_output'),
    ]

    operations = [
        migrations.CreateModel(
            name='FiPnMhPmthsetup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_type', models.CharField(max_length=3)),
                ('bill_mth', models.IntegerField()),
                ('bill_yr', models.IntegerField()),
                ('bill_process_flg', models.IntegerField(default=0)),
                ('bill_close_flg', models.IntegerField(default=0)),
                ('date_created', models.DateField(blank=True, null=True)),
                ('created_by', models.CharField(blank=True, default='', max_length=5)),
                ('date_modified', models.DateField(blank=True, null=True)),
                ('modified_by', models.CharField(blank=True, default='', max_length=5)),
            ],
            options={
                'verbose_name': 'Pension bill month setup',
                'db_table': 'fi_pn_mh_pmthsetup',
                'constraints': [models.UniqueConstraint(fields=('bill_type', 'bill_mth', 'bill_yr'), name='uniq_pmthsetup_key')],
            },
        ),
        migrations.CreateModel(
            name='FiPnThPensionBill',
            fields=[
                ('bill_no', models.CharField(max_length=22, primary_key=True, serialize=False)),
                ('bill_type', models.CharField(max_length=3)),
                ('bill_month', models.IntegerField()),
                ('bill_yr', models.IntegerField()),
                ('bank_cd', models.CharField(blank=True, default='', max_length=6)),
                ('total_amt_earned', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('total_amt_deducted', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('bill_abstract_no', models.CharField(blank=True, default='', max_length=22)),
                ('abstract_type', models.CharField(blank=True, default='', max_length=2)),
                ('cheque_no', models.IntegerField(blank=True, null=True)),
                ('cheque_dt', models.DateField(blank=True, null=True)),
                ('cheque_amt', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('date_created', models.DateField(blank=True, null=True)),
                ('created_by', models.CharField(blank=True, default='', max_length=5)),
                ('date_modified', models.DateField(blank=True, null=True)),
                ('modified_by', models.CharField(blank=True, default='', max_length=5)),
                ('remarks', models.CharField(blank=True, default='', max_length=100)),
                ('voucher_no', models.CharField(blank=True, default='', max_length=25)),
                ('abstract_date', models.DateField(blank=True, null=True)),
                ('gen_lic_tag', models.CharField(blank=True, default='', max_length=1)),
                ('posted', models.CharField(blank=True, default='', max_length=1)),
                ('posted_on', models.DateField(blank=True, null=True)),
                ('posted_by', models.CharField(blank=True, default='', max_length=5)),
            ],
            options={
                'verbose_name': 'Pension bill header',
                'db_table': 'fi_pn_th_pension_bill',
                'ordering': ['-bill_yr', '-bill_month', 'bill_no'],
                'indexes': [models.Index(fields=['bill_yr', 'bill_month', 'bill_type'], name='fi_pn_th_pe_bill_yr_1edf39_idx')],
            },
        ),
    ]
