# Generated by Django 5.2.12 on 2026-06-16 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_pension', '0014_pension_bill_tables'),
    ]

    operations = [
        migrations.CreateModel(
            name='FiPnTdJv',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('voucher_no', models.CharField(db_index=True, max_length=25)),
                ('voucher_dt', models.DateField()),
                ('yr', models.IntegerField()),
                ('mth', models.IntegerField()),
                ('sl_no', models.IntegerField()),
                ('zonal_cd', models.IntegerField()),
                ('aloc_cd1', models.CharField(max_length=4)),
                ('aloc_cd2', models.CharField(blank=True, default='', max_length=4)),
                ('aloc_cd3', models.CharField(blank=True, default='', max_length=7)),
                ('dr_cr_flag', models.CharField(max_length=1)),
                ('type_cd', models.IntegerField(default=1)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('ref', models.CharField(blank=True, default='', max_length=25)),
                ('remarks', models.CharField(blank=True, default='', max_length=60)),
                ('created_by', models.CharField(blank=True, default='', max_length=5)),
                ('created_on', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Pension journal voucher line',
                'db_table': 'fi_pn_td_jv',
                'ordering': ['voucher_no', 'sl_no'],
                'constraints': [models.UniqueConstraint(fields=('voucher_no', 'sl_no'), name='uniq_pn_td_jv_line')],
            },
        ),
        migrations.CreateModel(
            name='FiPnThJv',
            fields=[
                ('voucher_no', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('yr', models.IntegerField()),
                ('mth', models.IntegerField()),
                ('voucher_dt', models.DateField()),
                ('tran_type', models.CharField(blank=True, default='', max_length=10)),
                ('ref_no', models.CharField(blank=True, db_index=True, default='', max_length=25)),
                ('ref_dt', models.DateField(blank=True, null=True)),
                ('narration', models.CharField(blank=True, default='', max_length=500)),
                ('tot_amt', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('created_by', models.CharField(blank=True, default='', max_length=5)),
                ('created_on', models.DateField(blank=True, null=True)),
                ('voucher_for', models.CharField(blank=True, default='P', max_length=1)),
            ],
            options={
                'verbose_name': 'Pension journal voucher',
                'db_table': 'fi_pn_th_jv',
                'ordering': ['-yr', '-mth', 'voucher_no'],
                'indexes': [models.Index(fields=['yr', 'mth'], name='fi_pn_th_jv_yr_8e8695_idx')],
            },
        ),
    ]
