# Generated by Django 5.2.12 on 2026-06-22 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_pension', '0019_fi_pn_th_salout'),
    ]

    operations = [
        migrations.CreateModel(
            name='FiPnMdCommrateRupee',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('age_yrs', models.IntegerField(db_index=True)),
                ('wef_dt', models.DateField()),
                ('amt_per_rupee', models.DecimalField(blank=True, decimal_places=6, max_digits=14, null=True)),
                ('date_created', models.DateField(blank=True, null=True)),
                ('created_by', models.CharField(blank=True, default='', max_length=5)),
                ('date_modified', models.DateField(blank=True, null=True)),
                ('modified_by', models.CharField(blank=True, default='', max_length=5)),
            ],
            options={
                'verbose_name': 'Commutation rate per rupee (age)',
                'db_table': 'fi_pn_md_commrate_rupee',
                'ordering': ['age_yrs', '-wef_dt'],
                'managed': False,
            },
        ),
        migrations.RenameIndex(
            model_name='fipnthsalout',
            new_name='fi_pn_th_sa_emp_cd_b467a9_idx',
            old_name='fi_pn_th_salout_emp_yr_mth_idx',
        ),
        migrations.RenameIndex(
            model_name='fipnthsepcom',
            new_name='fi_pn_th_se_emp_cd_5744e3_idx',
            old_name='fi_pn_th_se_emp_cd_8a1f2d_idx',
        ),
        migrations.RenameIndex(
            model_name='fipnthsepcom',
            new_name='fi_pn_th_se_bill_no_962362_idx',
            old_name='fi_pn_th_se_bill_no_idx',
        ),
    ]
