# Generated by Django 5.2.12 on 2026-06-24 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_pension', '0021_fiprmhadaratevw'),
    ]

    operations = [
        migrations.CreateModel(
            name='FiPrTdSalout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_cd', models.CharField(db_index=True, max_length=5)),
                ('sal_mth', models.IntegerField()),
                ('sal_yr', models.IntegerField()),
                ('earndedn_cd', models.CharField(max_length=3)),
                ('earndedn_type', models.CharField(blank=True, default='', max_length=1)),
                ('no_of_units', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('rate', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('rate_pct_flg', models.IntegerField(blank=True, null=True)),
                ('act_earndedn_amt', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('adj_earndedn_amt', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('arr_earn_amt', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('notional_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('date_created', models.DateField(blank=True, null=True)),
                ('date_modified', models.DateField(blank=True, null=True)),
                ('modified_by', models.CharField(blank=True, default='', max_length=5)),
                ('created_by', models.CharField(blank=True, default='', max_length=5)),
            ],
            options={
                'verbose_name': 'Payroll salout line (Oracle mirror)',
                'db_table': 'fi_pr_td_salout',
                'ordering': ['emp_cd', '-sal_yr', '-sal_mth', 'earndedn_cd'],
                'indexes': [models.Index(fields=['emp_cd', 'sal_yr', 'sal_mth'], name='fi_pr_td_sa_emp_cd_52b82d_idx')],
                'constraints': [models.UniqueConstraint(fields=('emp_cd', 'sal_mth', 'sal_yr', 'earndedn_cd'), name='uniq_pr_td_salout_key')],
            },
        ),
        migrations.CreateModel(
            name='FiPrThSalout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_cd', models.CharField(db_index=True, max_length=5)),
                ('sal_mth', models.IntegerField()),
                ('sal_yr', models.IntegerField()),
                ('fa_no', models.CharField(blank=True, default='', max_length=5)),
                ('sal_bill_no', models.CharField(blank=True, default='', max_length=20)),
                ('gross_earn_amt', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('gross_dedn_amt', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('net_earn_amt', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('scale_desc', models.CharField(blank=True, default='', max_length=40)),
                ('basic_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('wg_st_dt', models.DateField(blank=True, null=True)),
                ('wg_end_dt', models.DateField(blank=True, null=True)),
                ('date_created', models.DateField(blank=True, null=True)),
                ('date_modified', models.DateField(blank=True, null=True)),
                ('modified_by', models.CharField(blank=True, default='', max_length=5)),
                ('created_by', models.CharField(blank=True, default='', max_length=5)),
            ],
            options={
                'verbose_name': 'Payroll salout header (Oracle mirror)',
                'db_table': 'fi_pr_th_salout',
                'ordering': ['emp_cd', '-sal_yr', '-sal_mth'],
                'indexes': [models.Index(fields=['emp_cd', 'sal_yr', 'sal_mth'], name='fi_pr_th_sa_emp_cd_c19652_idx')],
                'constraints': [models.UniqueConstraint(fields=('emp_cd', 'sal_mth', 'sal_yr'), name='uniq_pr_th_salout_key')],
            },
        ),
    ]
