# Generated by Django 5.2.12 on 2026-07-16 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Methodology2Consolidation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_cd', models.CharField(db_index=True, max_length=5, unique=True)),
                ('name', models.CharField(blank=True, default='', max_length=200)),
                ('case_no', models.CharField(blank=True, default='', max_length=20)),
                ('roll_no', models.CharField(blank=True, default='', max_length=30)),
                ('retirement_date', models.DateField(blank=True, null=True)),
                ('category', models.CharField(blank=True, default='', max_length=20)),
                ('designation', models.CharField(blank=True, default='', max_length=200)),
                ('tqs_yr', models.IntegerField(blank=True, null=True)),
                ('tqs_month', models.IntegerField(blank=True, null=True)),
                ('tqs_days', models.IntegerField(blank=True, null=True)),
                ('average_pay', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('last_pay', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('scale', models.CharField(blank=True, default='', max_length=100)),
                ('start_revision', models.CharField(blank=True, default='', max_length=60)),
                ('revision_blocks', models.JSONField(blank=True, default=list)),
                ('calculation_rows', models.JSONField(blank=True, default=list)),
                ('m2_basic_2017', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('m2_basic_2022', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('m2_pension_277', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('m2_pension_359', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('m2_family_pension_277', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('m2_family_pension_359', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('m1_family_pension_277', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('m1_family_pension_359', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('diff_family_pension_277', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('diff_family_pension_359', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('calculated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Methodology 2 consolidation snapshot',
                'db_table': 'methodology2_consolidation',
                'ordering': ['-updated_at'],
            },
        ),
    ]
