# Generated by Django 5.2.12 on 2026-07-16 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('methodology2', '0001_consolidation_snapshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='methodology2consolidation',
            name='is_employee_pension',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='methodology2consolidation',
            name='pensioner_name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='methodology2consolidation',
            name='wage_emp_name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
