"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.12.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path
from datetime import timedelta

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get(
    "DJANGO_SECRET_KEY",
    "django-insecure-g8#5k_t-3-o21#+am8nflt%q6sy&uvo)t#0%qe*p-5cht1qgv8",
)

DEBUG = os.environ.get("DJANGO_DEBUG", "True").lower() in (
    "1",
    "true",
    "yes",
)

ALLOWED_HOSTS = [
    h.strip()
    for h in os.environ.get("DJANGO_ALLOWED_HOSTS", "*").split(",")
    if h.strip()
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'corsheaders',
    'api',
    'accounts',
    'employee',
    'workflow',
    'audit',
    'first_pension',
    'family_pension',
    'methodology1',
    'methodology2',
    'M2_oldage_arrear.apps.M2OldageArrearConfig',
    'master_data',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]
CORS_ALLOW_ALL_ORIGINS = True

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        #'NAME': os.environ.get('MYSQL_DATABASE', 'smpk_pension'),
        'NAME': os.environ.get('MYSQL_DATABASE', 'finance'),
        'USER': os.environ.get('MYSQL_USER', 'root'),
        'PASSWORD': os.environ.get('MYSQL_PASSWORD', 'root123'),
        'HOST': os.environ.get('MYSQL_HOST', 'localhost'),
        'PORT': os.environ.get('MYSQL_PORT', '3306'),
        'OPTIONS': {
            'init_command': "SET sql_mode ='STRICT_TRANS_TABLES'",
        },
    },
    # Oracle FINANCE dump — historical first-pension archive (read-only).
    'finance': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': os.environ.get('FINANCE_MYSQL_DATABASE', 'finance'),
        'USER': os.environ.get('FINANCE_MYSQL_USER', os.environ.get('MYSQL_USER', 'root')),
        'PASSWORD': os.environ.get(
            'FINANCE_MYSQL_PASSWORD',
            os.environ.get('MYSQL_PASSWORD', 'root123'),
        ),
        'HOST': os.environ.get('FINANCE_MYSQL_HOST', 'localhost'),
        'PORT': os.environ.get('FINANCE_MYSQL_PORT', '3307'),
        'OPTIONS': {
            'init_command': "SET sql_mode ='STRICT_TRANS_TABLES'",
        },
    },
}

ORACLE_DB = {
    "HOST": os.environ.get("ORACLE_DB_HOST", "192.168.4.62"),
    "PORT": int(os.environ.get("ORACLE_DB_PORT", "1521")),
    # Live finance service (was kopttest for UAT; production SID is koptfin).
    "SERVICE_NAME": os.environ.get("ORACLE_DB_SERVICE_NAME", "koptfin"),
    "USER": os.environ.get("ORACLE_DB_USER", "system"),
    "PASSWORD": os.environ.get("ORACLE_DB_PASSWORD", "system"),
}

ORACLE_LOCAL_CACHE_ENABLED = os.environ.get(
    "ORACLE_LOCAL_CACHE_ENABLED", "True"
).lower() in ("1", "true", "yes")

ORACLE_SYNC_REQUIRED = os.environ.get("ORACLE_SYNC_REQUIRED", "False").lower() in (
    "1",
    "true",
    "yes",
)

# Live Oracle reads (employee search, salout transfer, ADA rates). Default off:
# SMPK saves pension data in MySQL; mirrors supply master data when Oracle is down.
ORACLE_READ_ENABLED = os.environ.get("ORACLE_READ_ENABLED", "False").lower() in (
    "1",
    "true",
    "yes",
)



# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
}

SIMPLE_JWT = {

    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=120),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=1),
}

AUTH_USER_MODEL = 'accounts.User'

# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = os.environ.get("DJANGO_TIME_ZONE", "Asia/Kolkata")

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Methodology-2 bulk PDFs: parent of M2_YYYY-MM-DD (default Desktop).
_bulk_out = (os.environ.get("BULK_OUTPUT_DIR") or "").strip()
BULK_OUTPUT_DIR = Path(_bulk_out) if _bulk_out else (Path.home() / "Desktop")
# Host path shown in UI when container writes to BULK_OUTPUT_DIR (Docker).
BULK_OUTPUT_HOST_HINT = (os.environ.get("BULK_OUTPUT_HOST_HINT") or "").strip()


def display_bulk_output_dir(container_path) -> str:
    """Map container /output/... to host Desktop path for API responses."""
    raw = str(container_path or "")
    hint = BULK_OUTPUT_HOST_HINT
    if not hint:
        return raw
    parent = str(BULK_OUTPUT_DIR).replace("\\", "/").rstrip("/")
    out = raw.replace("\\", "/")
    if out != parent and not out.startswith(parent + "/"):
        return raw
    rest = out[len(parent) :].lstrip("/")
    sep = "\\" if "\\" in hint else "/"
    base = hint.rstrip("\\/")
    return f"{base}{sep}{rest.replace('/', sep)}" if rest else base
