# Generated by Django 5.2.12 on 2026-06-10 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FiPmMhBank',
            fields=[
                ('bank_cd', models.CharField(db_column='BANK_CD', max_length=6, primary_key=True, serialize=False, verbose_name='Bank code')),
                ('bank_desc', models.CharField(blank=True, db_column='BANK_DESC', default='', max_length=50, verbose_name='Bank description')),
                ('bank_id', models.CharField(blank=True, db_column='BANK_ID', default='', max_length=7, verbose_name='Bank ID')),
                ('control_bank_cd', models.CharField(blank=True, db_column='CONTROL_BANK_CD', default='', max_length=6, verbose_name='Control bank code')),
                ('addr1', models.CharField(blank=True, db_column='ADDR1', default='', max_length=25, verbose_name='Address 1')),
                ('addr2', models.CharField(blank=True, db_column='ADDR2', default='', max_length=25, verbose_name='Address 2')),
                ('ps', models.CharField(blank=True, db_column='PS', default='', max_length=30, verbose_name='P.S.')),
                ('city', models.CharField(blank=True, db_column='CITY', default='', max_length=20, verbose_name='City')),
                ('dist', models.CharField(blank=True, db_column='DIST', default='', max_length=20, verbose_name='District')),
                ('state', models.CharField(blank=True, db_column='STATE', default='', max_length=20, verbose_name='State')),
                ('pin', models.IntegerField(blank=True, db_column='PIN', null=True, verbose_name='PIN')),
                ('country', models.CharField(blank=True, db_column='COUNTRY', default='', max_length=20, verbose_name='Country')),
                ('contact1', models.CharField(blank=True, db_column='CONTACT1', default='', max_length=15, verbose_name='Contact 1')),
                ('contact2', models.CharField(blank=True, db_column='CONTACT2', default='', max_length=15, verbose_name='Contact 2')),
                ('fax_no', models.CharField(blank=True, db_column='FAX_NO', default='', max_length=15, verbose_name='Fax no.')),
                ('email_id', models.CharField(blank=True, db_column='EMAIL_ID', default='', max_length=30, verbose_name='Email')),
                ('date_created', models.DateField(blank=True, db_column='DATE_CREATED', null=True, verbose_name='Date created')),
                ('date_modified', models.DateField(blank=True, db_column='DATE_MODIFIED', null=True, verbose_name='Date modified')),
                ('modified_by', models.CharField(blank=True, db_column='MODIFIED_BY', default='', max_length=5, verbose_name='Modified by')),
                ('created_by', models.CharField(blank=True, db_column='CREATED_BY', default='', max_length=5, verbose_name='Created by')),
                ('rbi_cd', models.CharField(blank=True, db_column='RBI_CD', default='', max_length=9, verbose_name='RBI code')),
                ('old_bank_cd', models.CharField(blank=True, db_column='OLD_BANK_CD', default='', max_length=6, verbose_name='Old bank code')),
            ],
            options={
                'verbose_name': 'Bank branch (FI_PM_MH_BANK)',
                'verbose_name_plural': 'Bank branches (FI_PM_MH_BANK)',
                'db_table': 'fi_pm_mh_bank',
                'ordering': ['bank_desc', 'bank_cd'],
            },
        ),
        migrations.CreateModel(
            name='FiPmMhBankAbbr',
            fields=[
                ('bank_type', models.CharField(db_column='BANK_TYPE', max_length=2, primary_key=True, serialize=False, verbose_name='Bank type')),
                ('bank_name', models.CharField(blank=True, db_column='BANK_NAME', default='', max_length=60, verbose_name='Bank name')),
                ('created_by', models.CharField(blank=True, db_column='CREATED_BY', default='', max_length=5, verbose_name='Created by')),
                ('modified_by', models.CharField(blank=True, db_column='MODIFIED_BY', default='', max_length=5, verbose_name='Modified by')),
                ('date_created', models.DateField(blank=True, db_column='DATE_CREATED', null=True, verbose_name='Date created')),
                ('date_modified', models.DateField(blank=True, db_column='DATE_MODIFIED', null=True, verbose_name='Date modified')),
                ('bank_id', models.CharField(blank=True, db_column='BANK_ID', default='', max_length=3, verbose_name='Bank ID')),
                ('bank_short_name', models.CharField(blank=True, db_column='BANK_SHORT_NAME', default='', max_length=10, verbose_name='Short name')),
            ],
            options={
                'verbose_name': 'Bank abbreviation (FI_PM_MH_BANKABBR)',
                'verbose_name_plural': 'Bank abbreviations (FI_PM_MH_BANKABBR)',
                'db_table': 'fi_pm_mh_bankabbr',
                'ordering': ['bank_name', 'bank_type'],
            },
        ),
    ]
