# Generated by Django 5.2.12 on 2026-06-10 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FiPnMhEarndedn',
            fields=[
                ('earndedn_cd', models.CharField(db_column='EARNDEDN_CD', max_length=3, primary_key=True, serialize=False, verbose_name='Earn/dedn code')),
                ('earndedn_type', models.CharField(choices=[('E', 'Earning'), ('D', 'Deduction')], db_column='EARNDEDN_TYPE', max_length=1, verbose_name='Type')),
                ('earndedn_desc', models.CharField(blank=True, db_column='EARNDEDN_DESC', default='', max_length=100, verbose_name='Description')),
                ('date_created', models.DateField(blank=True, db_column='DATE_CREATED', null=True, verbose_name='Date created')),
                ('date_modified', models.DateField(blank=True, db_column='DATE_MODIFIED', null=True, verbose_name='Date modified')),
                ('modified_by', models.CharField(blank=True, db_column='MODIFIED_BY', default='', max_length=5, verbose_name='Modified by')),
                ('created_by', models.CharField(blank=True, db_column='CREATED_BY', default='', max_length=5, verbose_name='Created by')),
            ],
            options={
                'verbose_name': 'Earn/dedn code (FI_PN_MH_EARNDEDN)',
                'verbose_name_plural': 'Earn/dedn codes (FI_PN_MH_EARNDEDN)',
                'db_table': 'fi_pn_mh_earndedn',
                'ordering': ['earndedn_cd'],
            },
        ),
    ]
