# Generated by Django 5.2.12 on 2026-06-16 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0003_pension_master_tables'),
    ]

    operations = [
        migrations.CreateModel(
            name='FiPnMhJrnltype',
            fields=[
                ('date_created', models.DateField(blank=True, db_column='DATE_CREATED', null=True, verbose_name='Date created')),
                ('date_modified', models.DateField(blank=True, db_column='DATE_MODIFIED', null=True, verbose_name='Date modified')),
                ('modified_by', models.CharField(blank=True, db_column='MODIFIED_BY', default='', max_length=5, verbose_name='Modified by')),
                ('created_by', models.CharField(blank=True, db_column='CREATED_BY', default='', max_length=5, verbose_name='Created by')),
                ('jrnal_srl_no', models.IntegerField(db_column='JRNAL_SRL_NO', primary_key=True, serialize=False)),
                ('type', models.CharField(db_column='TYPE', max_length=6)),
                ('jrnal_desc', models.CharField(blank=True, db_column='JRNAL_DESC', default='', max_length=30)),
            ],
            options={
                'verbose_name': 'Journal type (FI_PN_MH_JRNLTYPE)',
                'db_table': 'fi_pn_mh_jrnltype',
                'ordering': ['jrnal_srl_no'],
            },
        ),
        migrations.AddField(
            model_name='fipnmhearndedn',
            name='alloc_cd',
            field=models.CharField(blank=True, db_column='ALLOC_CD', default='', max_length=4, verbose_name='Allocation code'),
        ),
        migrations.AddField(
            model_name='fipnmhearndedn',
            name='zonal_cd',
            field=models.IntegerField(blank=True, db_column='ZONAL_CD', null=True, verbose_name='Zonal code'),
        ),
        migrations.CreateModel(
            name='FiPnMdJrnltype',
            fields=[
                ('date_created', models.DateField(blank=True, db_column='DATE_CREATED', null=True, verbose_name='Date created')),
                ('date_modified', models.DateField(blank=True, db_column='DATE_MODIFIED', null=True, verbose_name='Date modified')),
                ('modified_by', models.CharField(blank=True, db_column='MODIFIED_BY', default='', max_length=5, verbose_name='Modified by')),
                ('created_by', models.CharField(blank=True, db_column='CREATED_BY', default='', max_length=5, verbose_name='Created by')),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('jrnal_srl_no', models.IntegerField(db_column='JRNAL_SRL_NO', db_index=True)),
                ('zonal_cd', models.IntegerField(db_column='ZONAL_CD')),
                ('dr_cr_flg', models.CharField(db_column='DR_CR_FLG', max_length=1)),
                ('aloc_cd1', models.CharField(db_column='ALOC_CD1', max_length=4)),
                ('aloc_cd2', models.CharField(blank=True, db_column='ALOC_CD2', default='', max_length=4)),
                ('aloc_cd3', models.CharField(blank=True, db_column='ALOC_CD3', default='', max_length=7)),
                ('map_cd', models.CharField(blank=True, db_column='MAP_CD', default='', max_length=15)),
            ],
            options={
                'verbose_name': 'Journal allocation (FI_PN_MD_JRNLTYPE)',
                'db_table': 'fi_pn_md_jrnltype',
                'ordering': ['jrnal_srl_no', 'zonal_cd', 'aloc_cd1'],
                'constraints': [models.UniqueConstraint(fields=('jrnal_srl_no', 'zonal_cd', 'dr_cr_flg', 'aloc_cd1', 'aloc_cd2', 'aloc_cd3'), name='uniq_pn_md_jrnltype_key')],
            },
        ),
    ]
