# Generated by Django 5.2.12 on 2026-06-24 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0004_voucher_jv'),
    ]

    operations = [
        migrations.CreateModel(
            name='FiXxMhDept',
            fields=[
                ('dept_cd', models.CharField(db_column='DEPT_CD', max_length=2, primary_key=True, serialize=False)),
                ('dept_desc', models.CharField(blank=True, default='', max_length=100)),
                ('dept_short_desc', models.CharField(blank=True, default='', max_length=7)),
                ('date_created', models.DateField(blank=True, null=True)),
                ('date_modified', models.DateField(blank=True, null=True)),
                ('created_by', models.CharField(blank=True, default='', max_length=5)),
                ('modified_by', models.CharField(blank=True, default='', max_length=5)),
            ],
            options={
                'verbose_name': 'Department (FI_XX_MH_DEPT)',
                'verbose_name_plural': 'Departments (FI_XX_MH_DEPT)',
                'db_table': 'fi_xx_mh_dept',
                'ordering': ['dept_desc', 'dept_cd'],
            },
        ),
    ]
