# Generated by Django 5.2.12 on 2026-07-01 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0005_oracle_offline_mirrors'),
    ]

    operations = [
        migrations.CreateModel(
            name='FiPmMhPayscale',
            fields=[
                ('date_created', models.DateField(blank=True, db_column='DATE_CREATED', null=True, verbose_name='Date created')),
                ('date_modified', models.DateField(blank=True, db_column='DATE_MODIFIED', null=True, verbose_name='Date modified')),
                ('modified_by', models.CharField(blank=True, db_column='MODIFIED_BY', default='', max_length=5, verbose_name='Modified by')),
                ('created_by', models.CharField(blank=True, db_column='CREATED_BY', default='', max_length=5, verbose_name='Created by')),
                ('scale_cd', models.CharField(db_column='SCALE_CD', max_length=20, primary_key=True, serialize=False, verbose_name='Scale code')),
                ('scale_desc', models.CharField(blank=True, db_column='SCALE_DESC', default='', max_length=100, verbose_name='Scale description')),
            ],
            options={
                'verbose_name': 'Pay scale (FI_PM_MH_PAYSCALE)',
                'verbose_name_plural': 'Pay scales (FI_PM_MH_PAYSCALE)',
                'db_table': 'fi_pm_mh_payscale',
                'ordering': ['scale_cd'],
            },
        ),
    ]
