# Generated by Django 5.2.12 on 2026-05-06 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_diesnon'),
    ]

    operations = [
        migrations.AddField(
            model_name='diesnon',
            name='end_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
