# Generated by Django 5.2.12 on 2026-05-10 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PensionCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_code', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=200)),
                ('emp_class', models.CharField(max_length=20)),
                ('birth_date', models.DateField()),
                ('joining_date', models.DateField()),
                ('retirement_date', models.DateField()),
                ('designation', models.CharField(max_length=200)),
                ('scale', models.CharField(max_length=100)),
                ('last_basic', models.DecimalField(decimal_places=2, max_digits=12)),
                ('no_pay_days', models.IntegerField(default=0)),
                ('dies_non_days', models.IntegerField(default=0)),
                ('commutation_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('commutation_reason', models.TextField(blank=True, null=True)),
                ('status', models.CharField(default='INITIATED', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
