# Generated by Django 5.2.12 on 2026-06-09 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_pensioncase'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_cd', models.CharField(max_length=10, unique=True, verbose_name='Bank code')),
                ('bank_desc', models.CharField(max_length=200, verbose_name='Bank description')),
                ('date_created', models.DateField(auto_now_add=True)),
                ('created_by', models.CharField(blank=True, default='', max_length=5)),
                ('date_modified', models.DateField(blank=True, null=True)),
                ('modified_by', models.CharField(blank=True, default='', max_length=5)),
            ],
            options={
                'verbose_name': 'Bank master',
                'verbose_name_plural': 'Bank master (FI_PM_MH_BANK)',
                'db_table': 'fi_pm_mh_bank',
                'ordering': ['bank_desc', 'bank_cd'],
            },
        ),
    ]
