# Generated by Django 5.2.12 on 2026-06-09 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_bank_master'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bankmaster',
            name='id',
        ),
        migrations.AddField(
            model_name='bankmaster',
            name='bank_addr',
            field=models.CharField(blank=True, db_column='BANK_ADDR', default='', max_length=500, verbose_name='Bank address'),
        ),
        migrations.AddField(
            model_name='bankmaster',
            name='bank_type',
            field=models.CharField(blank=True, db_column='BANK_TYPE', default='', max_length=10, verbose_name='Bank type'),
        ),
        migrations.AddField(
            model_name='bankmaster',
            name='branch_name',
            field=models.CharField(blank=True, db_column='BRANCH_NAME', default='', max_length=200, verbose_name='Branch name'),
        ),
        migrations.AddField(
            model_name='bankmaster',
            name='ifsc_cd',
            field=models.CharField(blank=True, db_column='IFSC_CD', default='', max_length=11, verbose_name='IFSC code'),
        ),
        migrations.AddField(
            model_name='bankmaster',
            name='micr_cd',
            field=models.CharField(blank=True, db_column='MICR_CD', default='', max_length=15, verbose_name='MICR code'),
        ),
        migrations.AlterField(
            model_name='bankmaster',
            name='bank_cd',
            field=models.CharField(db_column='BANK_CD', max_length=10, primary_key=True, serialize=False, verbose_name='Bank code'),
        ),
        migrations.AlterField(
            model_name='bankmaster',
            name='bank_desc',
            field=models.CharField(db_column='BANK_DESC', max_length=200, verbose_name='Bank description'),
        ),
        migrations.AlterField(
            model_name='bankmaster',
            name='created_by',
            field=models.CharField(db_column='CREATED_BY', max_length=5, verbose_name='Created by'),
        ),
        migrations.AlterField(
            model_name='bankmaster',
            name='date_created',
            field=models.DateField(db_column='DATE_CREATED'),
        ),
        migrations.AlterField(
            model_name='bankmaster',
            name='date_modified',
            field=models.DateField(blank=True, db_column='DATE_MODIFIED', null=True, verbose_name='Modified date'),
        ),
        migrations.AlterField(
            model_name='bankmaster',
            name='modified_by',
            field=models.CharField(blank=True, db_column='MODIFIED_BY', default='', max_length=5, verbose_name='Modified by'),
        ),
    ]
