# Generated by Django 5.2.12 on 2026-06-10 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_bank_master_full_oracle'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BankMaster',
        ),
    ]
