# Generated by Django 5.2.12 on 2026-06-24 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0006_oracle_wave2_mirrors'),
    ]

    operations = [
        migrations.CreateModel(
            name='FiXxMhEmpData',
            fields=[
                ('emp_cd', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('dept_cd', models.CharField(blank=True, default='', max_length=2)),
                ('dept_desc', models.CharField(blank=True, default='', max_length=100)),
                ('budcntr_cd', models.CharField(blank=True, default='', max_length=3)),
                ('alloc_desc', models.CharField(blank=True, default='', max_length=100)),
                ('fa_no', models.CharField(blank=True, default='', max_length=5)),
                ('fa_desc', models.CharField(blank=True, default='', max_length=50)),
                ('srf_no', models.CharField(blank=True, default='', max_length=7)),
                ('emp_class', models.CharField(blank=True, db_column='class', default='', max_length=15)),
                ('name', models.CharField(blank=True, default='', max_length=62)),
                ('desig', models.CharField(blank=True, default='', max_length=30)),
                ('dob_text', models.CharField(blank=True, default='', max_length=10)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('join_dt_text', models.CharField(blank=True, default='', max_length=10)),
                ('ret_dt_text', models.CharField(blank=True, default='', max_length=10)),
            ],
            options={
                'verbose_name': 'Employee data (Oracle mirror)',
                'db_table': 'fi_xx_mh_emp_data',
                'ordering': ['emp_cd'],
            },
        ),
    ]
